apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: dev
  labels:
    app: myapp
    app.kubernetes.io/name: myapp
    managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
